### ISSUE TITLE
Symbols can not be friendly converted, like α  β

### ISSUE THREAD

**Issue by Yangchunyu01** [rdvojmoc/DinkToPdf#110]
If there are some symbols(eg. α  β...) in html content , it will be converted as black square as below.
Can someone help on this? Much appreciate.
![image](https://user-images.githubusercontent.com/28860471/81462622-83ebdd80-91e6-11ea-9230-f58262125b4a.png)

**Comment by Yangchunyu01** [comment]
Solved

**Comment by rodriguez90** [comment]
@Yangchunyu01 you could share the solution, I currently present the same problem

**Comment by Yangchunyu01** [comment]
you can try like below:
![Uploading image.png…]()

**Comment by Yangchunyu01** [comment]
you can try like this: add font tag
![image](https://user-images.githubusercontent.com/28860471/116217585-5e9c0a80-a77c-11eb-9660-9a6383b376a5.png)


Hope it works for you!
