### ISSUE TITLE
DinkToPDF is not working on Azzure

### ISSUE THREAD

**Issue by Emptycz** [rdvojmoc/DinkToPdf#123]
Hi. I have developed asp.net core 3.0 app and I am converting HTML to PDF. In localhost it's all working but afer I uploaded the project on Azzure server, it does not work. I tried to switch bit version of library but nothing happened. 

Project is running on Linux (Ubuntu) server. I have no clue why it is not working.

**Comment by inspire95** [comment]
Hi, did you fix this problem?

**Comment by Emptycz** [comment]
Yes I actually used different NuGet package. NuGet package I used and it's working is: Haukcode.DinkToPDF. 
Link to NuGet package: https://www.nuget.org/packages/Haukcode.DinkToPdf/1.1.2?_src=template

**Comment by inspire95** [comment]
Work! Thanks for your help, you made my day.
