### ISSUE TITLE
Endless progress after first generated

### ISSUE THREAD

**Issue by Just3F** [rdvojmoc/DinkToPdf#13]
After my first generate, when i have tried to generate pdf again i get endless process. If i have restarted project it work good again. But just for first generate. As i understand it have stopped at this string
`bool converted = Tools.DoConversion(converter);` 
or sometimes happens next -  The PDF report that is created is just html code and not a readable report

**Comment by rdvojmoc** [comment]
Please check if converter is singleton. For more details check isssue #10 .

**Comment by Just3F** [comment]
@rdvojmoc  Thanks! It helps me.
