### ISSUE TITLE
CSS styles are not applied through URL and Path both

### ISSUE THREAD

**Issue by ampan307** [rdvojmoc/DinkToPdf#14]
I tried passing CSS file URL and Path both in UserStyleSheet in WebSettings. It does not throw any error but my styles are also not applying.
I am running code in Docker.

**Comment by rdvojmoc** [comment]
If you prepare project which reproduce the issue I will investigate further. Should be fixed in wkhtmltopdf library. See [this](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1971)

**Comment by Franklin89** [comment]
@rdvojmoc I have the same issue. But only if running inside docker. If I start the application with `dotnet run`  or using Visual Studio it works. I am using the 0.12.4 wkhtmltopdf from this repository. In my Docker Images I install `libgdiplus`. And place the `libwkhtmltox.so` file into the root of the application. I get no errors nothing but styles are just not applied. So my guess is that something is missing on the Docker Image. Any suggestion?

**Comment by rdvojmoc** [comment]
Can you provide project which reproduce the issue? I assume that you provide correct absolute path when you run it on docker image.

**Comment by Franklin89** [comment]
@rdvojmoc I was using a `https` CDN for styles. That will not work... Also if you add a `img` tag with a `src` to a `https` image it will not render. If you use a image at a `http` route that will render. Any clue why?

**Comment by rdvojmoc** [comment]
It only occurs (`http/https` issue) when you run it in Docker container?

**Comment by Franklin89** [comment]
@rdvojmoc I just checked this out and yes this only happens inside of docker. If I run it with `dotnet run` the image gets rendered correctly. Any idea what the issue could be?

**Comment by rdvojmoc** [comment]
Which docker image you inherit from 'FROM ...' in your docker file. Can you post DOCKERFILE here?

**Comment by Franklin89** [comment]
I am using the official `microsoft/aspnetcore:2.0` image. This is my Dockerfile (using multistage dockerfiles for build):

```
FROM microsoft/aspnetcore-build:2.0 as publish
WORKDIR /app

COPY . ./

RUN npm install
RUN gulp default
RUN dotnet publish -c Release -o out

FROM microsoft/aspnetcore:2.0

WORKDIR /app
EXPOSE 80

COPY --from=publish /app/out .
COPY --from=publish /app/libwkhtmltox.so .
COPY --from=publish /app/libwkhtmltox.dll .
COPY --from=publish /app/libwkhtmltox.dylib .

RUN apt-get update
RUN apt-get -y install libgdiplus

HEALTHCHECK --interval=10s --timeout=3s --start-period=60s --retries=10 CMD curl --fail http://localhost/hc || exit 1

ENTRYPOINT ["dotnet", "Centric.dll"]
```

**Comment by heidermatos** [comment]
@Franklin89 Is this working for you?

**Comment by NickersWeb** [comment]
Was this ever fixed?
