### ISSUE TITLE
Download Generated PDF

### ISSUE THREAD

**Issue by YousifALF** [rdvojmoc/DinkToPdf#146]
Hello, 
How can I Download  the Generated PDF  Directly Without Viewing it  and then Download it,   
I used the "**Out**" Property in the **globalSettings** but it seems to be that it working only  from **localhost**, when uploaded the Site to the cloud server nothing got downloaded in the user local system and that makes sense since the code trying to generate it in the Server side , not in the user side, 
So can u plz let me know how to download it directly ? or even is that possible?
Thanks 
Yousif.

**Comment by Markuzy** [comment]
You can use something like
`byte[] myGeneratedData = _converter.Convert(myDoc);`

where `_converter `in my case is `IConverter converter` and `myDoc` is your instance of` HtmlToPdfDocument` class.

Once you get your byte[], you can then return it to your user directly from a http response.

**Comment by YousifALF** [comment]
thanks
