### ISSUE TITLE
Memory Courputing DinkToPdf

### ISSUE THREAD

**Issue by sangeethnandakumar** [rdvojmoc/DinkToPdf#156]
![image](https://user-images.githubusercontent.com/24974154/157387418-8ab18127-1ee2-4a70-92f6-c4a7a1cc58bb.png)

I'm trying to run a for loop for 24 HTML files to convert to PDF.
It runs success for first 3 files and then throws this error.

**Comment by sestacruz** [comment]
I have the same problem. Have you found any solution?

**Comment by sangeethnandakumar** [comment]
Yes. Change the library. This library is not actively maintained for years.

This is much better fully HTML5 compatible, Supports parallel conversion, Doesn't need extra dll linking as well as works seamlessly on Windows, Mac, and Linux. The only requirement is Chrome installed on the host system

https://github.com/Sicos1977/ChromiumHtmlToPdf

**Comment by EhsanRezaei1981** [comment]
What you can do is to use this implementation in your loop.

var converter = new BasicConverter(new PdfTools());
var globalSetting = new GlobalSettings
{
    ColorMode = ColorMode.Color,
    Orientation = Orientation.Portrait,
    PaperSize = PaperKind.A4,
};
var pdfBytes = converter.Convert(new HtmlToPdfDocument()
{
    GlobalSettings = globalSetting,
    Objects = {
        new ObjectSettings() {
            HtmlContent = template.ToString()
        }
    }
});
