### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by Ahmed-Raouf** [rdvojmoc/DinkToPdf#2]
Hi,

When trying to print a view putting [Authorization] attribute on its action, DinkToPdf doesn't have the authentication ticket when printing the page. It is redirected to Login page and print it.
              Objects = {
                    new ObjectSettings()
                    {
                        Page = $"http://{Request.Host}/TestPage/TestAction",
                    },
                }

        [Authorization]
        public IActionResult TestAction()
        {

Is there any solution for this issue?

**Comment by rdvojmoc** [comment]
Hi,

you could use LoadSettings which is part of ObjectSettings. Example:
```csharp
var cookies = new Dictionary<string, string>();
cookies.Add("Set-Cookie", "auth");
var doc = new HtmlToPdfDocument()
{
	GlobalSettings = {
		ColorMode = ColorMode.Grayscale,
		Orientation = Orientation.Portrait,
		PaperSize = PaperKind.A4,
		Margins = new MarginSettings() { Top = 10 },
	},
	Objects = {
		new ObjectSettings() {
			Page = "http://www.color-hex.com/",
			LoadSettings = new LoadSettings()
			{
				Cookies = cookies
			}
		}
	}
};
```

You must provide cookie if you are using Cookie based authorization.
For more details you can check [wkhtmltopdf issues](https://github.com/wkhtmltopdf/wkhtmltopdf/issues?utf8=%E2%9C%93&q=cookie) regarding cookies.

**Comment by Ahmed-Raouf** [comment]
It didn't work for me.
But I have a work around, as I called the action I want to print by ajax. When the View is rendered, its HTML is returned. then I passed it in another ajax call to the convertToPdf action which renders the HtmlContent and returns the pdf file.

            $("#printCert").click(function () { 

                $.ajax({
                    url: "/Certificate/Print",
                    contentType: false,
                    processData: false,
                    success: function (result) {

                        var model = new FormData();
                        model.append("html", result);
                        model.append("f", 'UnionCertificate.pdf');

                        $.ajax({
                            url: "/Certificate/pdfConvertHtmlContent",
                            contentType: false,
                            processData: false,
                            data: model,
                            type: "POST",
                            success: function (result) {
                                var link = document.createElement('a');
                                link.href = "data:application/pdf;base64," + result;
                                var fileName = "Certificate.pdf";
                                link.download = fileName;
                                link.click();

                            }, error: function (result) {
                        
                            }
                        });

                    }, error: function (result) {
                        alert('error');
                    }
                });

            });

**Comment by MostafaRamadan1** [comment]
A solution for this in asp.net core 2.1 would be, in you method inside the controller,

```
public IActionResult PdfTest()
        {
           //Convert existing cookies to dictionary
           IRequestCookieCollection cookies = Request.Cookies;
            var cookiesDic = new Dictionary<string, string>();
            foreach (var cookie in cookies) {
                cookiesDic.Add(cookie.Key, cookies[cookie.Key]);
            }

var doc = new HtmlToPdfDocument()
{
	GlobalSettings = {
		ColorMode = ColorMode.Grayscale,
		Orientation = Orientation.Portrait,
		PaperSize = PaperKind.A4,
		Margins = new MarginSettings() { Top = 10 },
	},
	Objects = {
		new ObjectSettings() {
			Page = "http://www.color-hex.com/",
			LoadSettings = new LoadSettings()
			{
				Cookies = cookiesDic
			}
		}
	}
};

}

```
Hope it works for all of you :)
