### ISSUE TITLE
Setting PagesCount to false causes crash

### ISSUE THREAD

**Issue by Jacquers** [rdvojmoc/DinkToPdf#22]
If I set PagesCount to false it crashes. The error messages says pdftools not found and a divide by 0 error. 

I can get around it with the following:

new ObjectSettings()
                    {
                        PagesCount = true,
                        HtmlContent = html,
                        WebSettings =
                        {
                            DefaultEncoding = "utf-8"
                        },
                        HeaderSettings =
                        {
                            FontSize = 9,
                            //Right = "Page [page] of [toPage]",
                            Right = "",
                            Line = false,
                            Spacing = 0
                        }
                    }

**Comment by rdvojmoc** [comment]
I can confirm the issues. Can you maybe post this problem to [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/issues). Issue is coming from wkhtmltopdf library and not DinkToPdf.

**Comment by fabs-rodriguez** [comment]
I am getting that error too when setting PagesCount to zero. Jacquers, did you post the problem to wkhtmltopdf? I didn't see the issue there... I will post it now...
