### ISSUE TITLE
using font-face

### ISSUE THREAD

**Issue by rivkawaxman** [rdvojmoc/DinkToPdf#24]
I am trying to include a font from a ttf file. 
I put the ttf file in the wwwroot folder of my project and i have this in my css in my html file:
@font-face {
            font-family: 'MICR';
            src: url("micrenc.ttf") format("truetype");
            font-weight: normal;
            font-style: normal;
        }
and this on the line that needs the font:
 style="font-family: 'MICR'; font-size: 30px;

The pdf file does that is created does even not include the text that is supposed to be in that font.
(when i render this file in my browser, i do see the text and in the specified font)

**Comment by rdvojmoc** [comment]
Can you try with other font format than .ttf, for example ,woff? Look at this [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1600)

**Comment by rivkawaxman** [comment]
Thanks. However that did not work for me. Am I putting the font file in the right place?

**Comment by rdvojmoc** [comment]
Please prepare reproducible project and I could take a look.

**Comment by rivkawaxman** [comment]
Ok here is a test project which resembles my project
https://github.com/rivkawaxman/pdf_convert
Thank you.

**Comment by rdvojmoc** [comment]
Replace your `Get ` method with this one:
```csharp
public async Task<IActionResult> Get()
        {
            await Task.CompletedTask;

            string cssPath = @"file:///" + _hostingEnvironment.ContentRootPath + @"\wwwroot\fonts.css";

            string html = "<!DOCTYPE html>" +
                          "<html lang = \"en\">" +
                               "<head>" +
                                    "<meta charset = \"UTF-8\">" +
                                    "<title> Check </title>" +
                                    "<link href='" + cssPath + "' rel='stylesheet' type='text/css' media='screen'>" +
                               "</head>" +
                              "<body>" +
                                    "<div style = \"text-align: center; margin-top:16px;\">" +
                                        "<p style=\"font-family: 'MICR Encoding', sans-serif; font-size: 30px;\"> 235 384756  13425346 9877</p>" +
                                    "</div>" +
                                    "<div style = \"text-align: center; margin-top:16px;\">" +
                                        "<p style=\"font-size: 30px;\"> This line doesn not have a font specified</p>" +
                                    "</div>" +
                              "</body>" +
                          "</html>";
            

            var pdf = new HtmlToPdfConverterService(_converter).Convert(html);
            var path = Path.Combine(_hostingEnvironment.WebRootPath, "micr.pdf");
            using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write))
            {
                fs.Write(pdf, 0, pdf.Length);
            }
            return Ok();
        }
```

As far I know wkhtmltopdf doesn't support relative paths for that reason I added `cssPath` variable to tell where to look for css file.

In `wwwroot` create `fonts.css` and paste this code:
```
@font-face {
    font-family: 'MICR Encoding';
    font-style: normal;
    font-weight: normal;
    src: url(./micrenc.woff) format('woff');
}
```
[Here ](https://github.com/rdvojmoc/DinkToPdf/files/1675223/micr.pdf) is the result of the conversion.

**Comment by rivkawaxman** [comment]
Thank you so much! It's working!

**Comment by kgrosvenor** [comment]
Is this a cross platform solution @rivkawaxman i.e linux, mac?

**Comment by ghost** [comment]
I tried the solution, using external css, but it's not working for me.
I have a method that generates the html with internal css(tried it with external css too).
If I create a basic html page using the html content generated, the font is used. 
The problem is that the pdf doesn't generate using the customFont(as the HTML does), it uses the next one, Arial.

```
@font-face{
                  font-family: 'customFont';
                  font-style: normal;
                  font-weight: normal;
                  src:url("C:/Users/user/Path/SometOtherPath/customFont.woff"); 
                  // Absolute path for internal css
                  // Relative path for external css 
}
body{
        font-family: 'customFont', Arial, Helvetica, sans-serif;
        font-size: 18px;
}
```
Is there anything I am missing?

EDIT: 
Weirdly enough, if I use a link reference to a css file, it works. That means I am not doing something right with the local css.

**Comment by hamedapp** [comment]
> Replace your `Get ` method with this one:
> 
> ```cs
> public async Task<IActionResult> Get()
>         {
>             await Task.CompletedTask;
> 
>             string cssPath = @"file:///" + _hostingEnvironment.ContentRootPath + @"\wwwroot\fonts.css";
> 
>             string html = "<!DOCTYPE html>" +
>                           "<html lang = \"en\">" +
>                                "<head>" +
>                                     "<meta charset = \"UTF-8\">" +
>                                     "<title> Check </title>" +
>                                     "<link href='" + cssPath + "' rel='stylesheet' type='text/css' media='screen'>" +
>                                "</head>" +
>                               "<body>" +
>                                     "<div style = \"text-align: center; margin-top:16px;\">" +
>                                         "<p style=\"font-family: 'MICR Encoding', sans-serif; font-size: 30px;\"> 235 384756  13425346 9877</p>" +
>                                     "</div>" +
>                                     "<div style = \"text-align: center; margin-top:16px;\">" +
>                                         "<p style=\"font-size: 30px;\"> This line doesn not have a font specified</p>" +
>                                     "</div>" +
>                               "</body>" +
>                           "</html>";
>             
> 
>             var pdf = new HtmlToPdfConverterService(_converter).Convert(html);
>             var path = Path.Combine(_hostingEnvironment.WebRootPath, "micr.pdf");
>             using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write))
>             {
>                 fs.Write(pdf, 0, pdf.Length);
>             }
>             return Ok();
>         }
> ```
> 
> As far I know wkhtmltopdf doesn't support relative paths for that reason I added `cssPath` variable to tell where to look for css file.
> 
> In `wwwroot` create `fonts.css` and paste this code:
> 
> ```
> @font-face {
>     font-family: 'MICR Encoding';
>     font-style: normal;
>     font-weight: normal;
>     src: url(./micrenc.woff) format('woff');
> }
> ```
> 
> [Here ](https://github.com/rdvojmoc/DinkToPdf/files/1675223/micr.pdf) is the result of the conversion.

Works for me

**Comment by sangib58** [comment]
In my case i am not able to use font family. Tried in possible all ways(internal css, external css, internal css) but nothing worked.Other css properties are working perfectly.I am using a method to get html. Thanks in advance.

public ActionResult CreatePDF(int id)
        {
            try
            {
                string host=Request.Scheme+"://"+Request.Host;
                var objGenerator=new CertificateGenerator(_context);

                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Landscape,
                    PaperSize = PaperKind.A4Small,
                    Margins = new MarginSettings { Top = 10 },
                    DocumentTitle = "",
                };
                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent =objGenerator.GetHTMLString(id,host),
                    //WebSettings = { DefaultEncoding = "utf-8"},
                    //WebSettings = { DefaultEncoding = "utf-8",LoadImages=true, UserStyleSheet =  Path.Combine(Directory.GetCurrentDirectory(), @"Resources","Assests", "styles.css") },
                    //HeaderSettings = { FontName = FontName, FontSize = 9, Right = "Page [page] of [toPage]", Line = true },
                    //FooterSettings = { FontName = FontName, FontSize = 9, Line = true, Center = "This is report footer for testing." },    
                };
                var pdf = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings }
                };
                var file = _converter.Convert(pdf);
                return File(file, "application/pdf");
            }
            catch (System.Exception)
            {        
                throw;
            }
        }

public string GetHTMLString(int id,string host)
        {
            var cssPath=Path.Combine(Directory.GetCurrentDirectory(), @"Resources","Assests", "styles.css");
            var objCertificate=_context.CertificateTemplates.FirstOrDefault(q=>q.CertificateTemplateId==id);
            var sb = new StringBuilder();
            sb.Append(@"<!DOCTYPE html>
                        <html>
                            <head>
                            <title>Certificate</title>
                                <style>
                                    body {background-image: url("
                                    +host+objCertificate.BackgroundImagePath+")};background-repeat: no-repeat;</style><link href='" + cssPath + "' rel='stylesheet' type='text/css'></head><body>");
                            if(objCertificate.TopLeftImagePath.Length>10 || objCertificate.TopRightImagePath.Length>10)
                                {
                                    sb.Append(@"<div class='topImages'>");
                                    if(objCertificate.TopLeftImagePath.Length>10)
                                    {
                                        sb.Append(@"<img class='imgTopLeft' src="+host+objCertificate.TopLeftImagePath+" alt='Left Logo'>");
                                    }
                                    if(objCertificate.TopRightImagePath.Length>10)
                                    {
                                        sb.Append(@"<img class='imgTopRight' src="+host+objCertificate.TopRightImagePath+" alt='Right Logo'>");
                                    }
                                    sb.Append(@"</div>");
                                }
                            sb.Append(@"<div class='title'>"+objCertificate.Title+"</div><div class='heading'>"+objCertificate.Heading+"</div><div class='mainText'>"+objCertificate.MainText+"</div>");
                            if(objCertificate.LeftSignatureImagePath.Length>10 || objCertificate.RightSignatureImagePath.Length>10)
                                {
                                    sb.Append(@"<div class='signatureImages'>");
                                    if(objCertificate.LeftSignatureImagePath.Length>10)
                                    {
                                        sb.Append(@"<img class='imgTopLeft' src="+host+objCertificate.LeftSignatureImagePath+" alt='Left Signature'>");
                                    }
                                    if(objCertificate.RightSignatureImagePath.Length>10)
                                    {
                                        sb.Append(@"<img class='imgTopRight' src="+host+objCertificate.RightSignatureImagePath+" alt='Right Signature'>");
                                    }
                                    sb.Append(@"</div>");
                                }
                            if(objCertificate.LeftSignatureText.Length>5 || objCertificate.RightSignatureText.Length>5)
                                {
                                    sb.Append(@"<div class='signatureHrTag'>");
                                    if(objCertificate.LeftSignatureText.Length>5)
                                    {
                                        sb.Append(@"<hr class='hrLeft'>");
                                    }
                                    if(objCertificate.RightSignatureText.Length>5)
                                    {
                                        sb.Append(@"<hr class='hrRight'>");
                                    }
                                    sb.Append(@"</div>");
                                }
                            if(objCertificate.LeftSignatureText.Length>5 || objCertificate.RightSignatureText.Length>5)
                                {
                                    sb.Append(@"<div class='signatureText'>");
                                    if(objCertificate.LeftSignatureText.Length>5)
                                    {
                                        sb.Append(@"<span class='textLeft'>"+objCertificate.LeftSignatureText+"</span>");
                                    }
                                    if(objCertificate.RightSignatureText.Length>5)
                                    {
                                        sb.Append(@"<span class='textRight'>"+objCertificate.RightSignatureText+"</span>");
                                    }
                                    sb.Append(@"</div>");
                                }
                            sb.Append(@"<div class='bottomText'>");
                                if(objCertificate.BottomMiddleImagePath.Length>10)
                                {
                                    sb.Append(@"<img class='imgBottomLeft' src="+host+objCertificate.BottomMiddleImagePath+" alt='Bottom Image'>");
                                }
                                sb.Append(@"<span class='textBottomMiddle'>TAPAS"+(objCertificate.CertificateTemplateId<10?('0'+objCertificate.CertificateTemplateId):objCertificate.CertificateTemplateId)+"</span>");
                                sb.Append(@"<span class='textBottomRight'>Printed on "+DateTime.Now+"</span>");
                            sb.Append(@"</div>");
                               
            sb.Append(@"      
                            </body>
                        </html>");
            return sb.ToString();
        }



body{
    font-family: 'Courier New', Courier, monospace;
}
.title {
    text-align: center;
    font-size: 40px;
    color: black;
    padding-bottom: 35px;
}
.heading {
    text-align: center;
    color: black;
    padding-bottom: 25px;
}
.mainText {
    /* font-variant: small-caps; */
    font-style: oblique;
    font-size: 25px;
    text-align: center;
    color: black;
    padding-bottom: 35px;
}
.topImages{
    padding-bottom: 120px;
}
.imgTopLeft{
    float:left;
    max-width: 150px;
    max-height: 150px;
}
.imgTopRight{
    float:right;
    max-width: 150px;
    max-height: 150px;
}
.signatureImages{
    padding-top: 120px;
}
.hrLeft{
    float:left;
    width: 300px;
}
.hrRight{
    float:right;
    width: 300px;
}
.signatureHrTag{
    padding-top: 80px;
}
.signatureText{
    padding-top: 20px;
}
.textLeft{
    float: left;
}
.textRight{
    float: right;
}
.bottomText{
    padding-top: 250px;
}
.imgBottomLeft{
    float:left;
    max-width: 150px;
    max-height: 150px;
}
.textBottomMiddle{
    padding-left: 400px;
}
.textBottomRight{
    padding-left: 400px;
}

**Comment by zanyar3** [comment]
> Replace your `Get ` method with this one:
> 
> ```cs
> public async Task<IActionResult> Get()
>         {
>             await Task.CompletedTask;
> 
>             string cssPath = @"file:///" + _hostingEnvironment.ContentRootPath + @"\wwwroot\fonts.css";
> 
>             string html = "<!DOCTYPE html>" +
>                           "<html lang = \"en\">" +
>                                "<head>" +
>                                     "<meta charset = \"UTF-8\">" +
>                                     "<title> Check </title>" +
>                                     "<link href='" + cssPath + "' rel='stylesheet' type='text/css' media='screen'>" +
>                                "</head>" +
>                               "<body>" +
>                                     "<div style = \"text-align: center; margin-top:16px;\">" +
>                                         "<p style=\"font-family: 'MICR Encoding', sans-serif; font-size: 30px;\"> 235 384756  13425346 9877</p>" +
>                                     "</div>" +
>                                     "<div style = \"text-align: center; margin-top:16px;\">" +
>                                         "<p style=\"font-size: 30px;\"> This line doesn not have a font specified</p>" +
>                                     "</div>" +
>                               "</body>" +
>                           "</html>";
>             
> 
>             var pdf = new HtmlToPdfConverterService(_converter).Convert(html);
>             var path = Path.Combine(_hostingEnvironment.WebRootPath, "micr.pdf");
>             using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write))
>             {
>                 fs.Write(pdf, 0, pdf.Length);
>             }
>             return Ok();
>         }
> ```
> 
> As far I know wkhtmltopdf doesn't support relative paths for that reason I added `cssPath` variable to tell where to look for css file.
> 
> In `wwwroot` create `fonts.css` and paste this code:
> 
> ```
> @font-face {
>     font-family: 'MICR Encoding';
>     font-style: normal;
>     font-weight: normal;
>     src: url(./micrenc.woff) format('woff');
> }
> ```
> 
> [Here ](https://github.com/rdvojmoc/DinkToPdf/files/1675223/micr.pdf) is the result of the conversion.

Work for me thanks,

**Important Note:**

Please ensure the font used is set by its name, not by renaming the file. Only TrueType fonts (TTF) are acceptable.

![image](https://github.com/user-attachments/assets/bb9ea20c-e0c3-4e77-addc-8988582937ae)
