### ISSUE TITLE
Header/Footer Html

### ISSUE THREAD

**Issue by snovak7** [rdvojmoc/DinkToPdf#26]
Is it possible to directly put Html for HeaderSettings, FooterSettings as-well? now it is only possible to link via HtmUrl.

**Comment by rdvojmoc** [comment]
Is not possible to pass HTML directly to the Header and Footer settings. For more details see issues on wkhtmltopdf page:
- [2879](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2879)
- [2280](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2280)

**Comment by elninoisback** [comment]
I can live with setting the header via HtmUrl, but is it possible to set the header height? It seems to be fixed.
