### ISSUE TITLE
Cannot add headers & footers

### ISSUE THREAD

**Issue by DaanAcohen** [rdvojmoc/DinkToPdf#29]
It is possible to put some content on each page as describe [here](https://github.com/rdvojmoc/DinkToPdf/issues/28) once the number of pages is known and when having an empty document initially. However, when having a big html, I would like to add headers and footers to the pages afterwards. I do not know the exact number of pages, I just want to ensure that once the pdf is generated each page has a header and a footer. This is a problem.
The normal content is presented correctly. It is just about adding headers and footers to each page afterwards. This[ html & css](https://stackoverflow.com/questions/1360869/how-to-use-html-to-print-header-and-footer-on-every-printed-page-of-a-document/4121962#4121962) should solve it but it is not working.

**Comment by rdvojmoc** [comment]
If we continue from #28 you could add header and footer like that:
```csharp
// set up the document
HtmlToPdfDocument doc = new HtmlToPdfDocument()
{
	GlobalSettings = {
		PaperSize = PaperKind.A4,
		Orientation = Orientation.Portrait,
		Margins = new MarginSettings() { Top = 10, Left = 10, Right = 10 },
	},
};

// add object settings to the document
foreach (var item in items)
{
	var page = new ObjectSettings()
	{
                // PagesCount must be true to use it on header and footer
		PagesCount = true,
                 // specifying HeaderSettings adds footer
		HeaderSettings = { Center = Guid.NewGuid().ToString(), Line = new Random().Next(100) % 2 == 0, Right = "Page [page] of [toPage]" },
                // specifying FooterSettings adds footer
		FooterSettings = { Center = Guid.NewGuid().ToString(), Line = new Random().Next(100) % 2 == 0, Right = "Page [page] of [toPage]" },
		WebSettings = { DefaultEncoding = "utf-8" },
		HtmlContent = item
	};
	doc.Objects.Add(page);
}

//convert
var pdf = _converter.Convert(doc);
```

[PDF](https://github.com/rdvojmoc/DinkToPdf/files/1724317/Issue.29.pdf) generated from code above.

**Comment by DaanAcohen** [comment]
Thanks for your quick reply but this does not work work me. I have a

-  string with html content (really one, **no list of items I can loop through**). There is a lot of content so it covers multiple pages.
- one header
- one footer

So I need a method like this:
```

public MemoryStream GenerateDocument(string aLotOfContentWhichRequiresMultiplePages, string genericHeader, string genericfooter)
{
      // Implementation?
}
```

**Comment by rdvojmoc** [comment]
Thanks for clarifying what is your use case. wkhtmltopdf doesn't support HTML strings in Header or Footer settings. For more on this you can check #26 . Stakcoverflow question that you linked talks about print selector. wkhtmltopdf by defaults uses screen selector. You can change this with `WebSettings.PrintMediaType=true`.

**Comment by sumit0501** [comment]
Hello,
Header and Footer are not coming on docker alpine image. Tried both with htmlurl or with Right=text option. It is coming on .netcore 2.1 runtime image but not with alpine. please help.

**Comment by AmbroiseCouissin** [comment]
We have the same issue @sumit0501

**Comment by AmbroiseCouissin** [comment]
@sumit0501 We solved it here: https://github.com/rdvojmoc/DinkToPdf/issues/53#issuecomment-516814742
