### ISSUE TITLE
Docker + .NET Core 2.0 + Https Images

### ISSUE THREAD

**Issue by dekim** [rdvojmoc/DinkToPdf#34]
I'm currently running DinkToPdf on my macOS without any problem.

My webpages use external HTTPS ressources such as 
- two images
- 1 CSS file

In Docker, using a asp-net-2.0 base image (along with added-dependencies

`apt-get install -y --no-install-recommends zlib1g fontconfig libfreetype6 libx11-6 libxext6 libxrender1`

For some reason, the PDF rendered has no image, and no CSS.

How can I fix this?

**Comment by dekim** [comment]
Docker reports 

`QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init`

**Comment by jinhduong** [comment]
Hi @dekim 
I also face the same problem after upgrade from docker image aspnetcore 1.1 to 2.0, how did you resolve this problem? Thanks.

**Comment by jinhduong** [comment]
Hi @dekim,
I also faced this problem after I upgrade my aspnetcore image from 1.1 to 2.0, how did you resolve this problem? thanks

**Comment by mike-dube** [comment]
@jinhduong Sadly it's not an issue with this project but with the lib wktopdf.

It does not support TLS 2.0, so it's impossible to load ressource in https. I had to use base64 image.

**Comment by jinhduong** [comment]
@dekim Thanks for your response, I found out the solution for aspnetcore2.0 image and it worked. If you still would like to use external https resources, you can try:
```
FROM microsoft/aspnetcore:2.0 AS base
RUN ["apt-get", "update"]
RUN ["apt-get", "-y", "install", "libgdiplus"]
RUN ["apt-get", "-y", "install", "xvfb", "libfontconfig", "wkhtmltopdf"]
RUN ["apt-get", "-y", "install", "libc6-dev"]
RUN ["apt-get", "-y", "install", "openssl"]
RUN ["apt-get", "-y", "install", "libssl1.0-dev"]
```

**Comment by mike-dube** [comment]
@jinhduong Thanks! Awesome work!

**Comment by irfanfarmaku** [comment]
> @dekim Thanks for your response, I found out the solution for aspnetcore2.0 image and it worked. If you still would like to use external https resources, you can try:
> 
> ```
> FROM microsoft/aspnetcore:2.0 AS base
> RUN ["apt-get", "update"]
> RUN ["apt-get", "-y", "install", "libgdiplus"]
> RUN ["apt-get", "-y", "install", "xvfb", "libfontconfig", "wkhtmltopdf"]
> RUN ["apt-get", "-y", "install", "libc6-dev"]
> RUN ["apt-get", "-y", "install", "openssl"]
> RUN ["apt-get", "-y", "install", "libssl1.0-dev"]
> ```

awesome, this is working on .net core 3.0 too
