### ISSUE TITLE
Small contents in PDF for macOS

### ISSUE THREAD

**Issue by kuthreecar** [rdvojmoc/DinkToPdf#42]
I am using DinkToPdf to convert my html to pdf and got a great result in windows. 
But in macOS I am facing a problem:  I put html file and the pdf that it produced became very small on A4 size paper.
I was testing on different websites and it had similar result. Like the following picture
![a1](https://user-images.githubusercontent.com/7273772/42919677-9a5c66b0-8b45-11e8-9a46-b004fcceaad0.png)
Any advise for me to fix the problems?

**Comment by rdvojmoc** [comment]
There were some problems with sizes on MacOS. Please see this [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3241). You could try setting DPI property of GlobalSettings to ~380dpi or something in close to it.

**Comment by kuthreecar** [comment]
Thanks, I already fixed it easily

**Comment by rdvojmoc** [comment]
Can you share how you fixed it? For future users that will have the same issue.

**Comment by kuthreecar** [comment]
As you said previously just need to adjust DPI in Global Setting, following is a part of my setting

> 	GlobalSettings = {
	ColorMode = DinkToPdf.ColorMode.Color,
	Orientation = Orientation.Portrait,
	PaperSize = PaperKind.A4,
	Margins = new MarginSettings() { Top = 10 },
	DPI = 380,
	Out = Path.Combine(reportDirectory, filename + ".pdf")
	},

**Comment by rdvojmoc** [comment]
Greate, thanks.

**Comment by QuintonC** [comment]
Still an active issue. Thanks for the solution @kuthreecar
