### ISSUE TITLE
How to deal with pagination when lines don't have a standard height

### ISSUE THREAD

**Issue by lnaie** [rdvojmoc/DinkToPdf#46]
I was wondering about that, if there is any know solution/workaround.
It could happen when the cell text gets wrapped because it has to be shown entirely. So it will affect the height of the rows (making it variable), therefore the number of rows that can fit in a page.

Is there a way to detect dynamically the height of the rows?

Thanks

**Comment by rdvojmoc** [comment]
Take a look on [wkhtmltopdf github](https://github.com/wkhtmltopdf/wkhtmltopdf/issues) for a clue. DinkToPdf is only wrapper for wkhtmltopdf library,

**Comment by ghost** [comment]
@lnaie I have the same problem. Did you find the solution?
