### ISSUE TITLE
Error when sending bytes to frontend

### ISSUE THREAD

**Issue by z-tc** [rdvojmoc/DinkToPdf#55]
I have an issue when getting data from .NET Web API controller. I am returning File(bytes, "application/pdf"), and on frontend i am getting error:

SyntaxError: Unexpected token % in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad, and response starts with "%PDF-1.4↵1 0 obj↵<<↵/Title (��".
Locally, file is saved without any problems. 

Any idea how can i solve this?

Thanks

**Comment by z-tc** [comment]
Ok, i solved my issue:
You need to set  responseType: 'arraybuffer' to http client, so frontend knows what to expect! Default is json, and because of that parsing went wrong in browser...

Hope that will help someone, cheers!

**Comment by ulukacher** [comment]
Hi, 
i am running through the same trouble. My controller method returns a FileContentResult: 
`return File(file, "application/pdf", fileName);` where file is a byte array. I got the same error you told above. Then, in my Angular POST request i added `responseType: 'arraybuffer'`  but the error doesn´t disappear.  Where did you set the responseType? 

Thank you
