### ISSUE TITLE
Pdf cannot view

### ISSUE THREAD

**Issue by jinhduong** [rdvojmoc/DinkToPdf#6]
After I have run the server then it show this error, but it still run.
![error1](https://user-images.githubusercontent.com/7991658/29858873-1039310e-8d92-11e7-86bb-e88202985acb.png)

Here is my code in the API, I scared it have problem with `async/await` so I used `.Result`
``` c#
[HttpGet("booking-preview/{bookingId}")]
public IActionResult GetBookingPreview(long bookingId)
{
	if (!ModelState.IsValid)
		return Ok(ModelState);

	var doc = new HtmlToPdfDocument()
	{
		GlobalSettings = {
			PaperSize = PaperKind.A3,
			Orientation = Orientation.Landscape,
		},

		Objects = {
			new ObjectSettings()
			{
				Page = "http://google.com/",
			},
			new ObjectSettings()
			{
				Page = "https://github.com/",

			}
		}
	};
	byte[] pdf = _converter.Convert(doc);
	return new FileContentResult(pdf, "application/pdf");
}
```

But after have called the API and then return the pdf file, I opened it by browser with`Blob` or using `Pdf reader` but it appeared `blank/ not support`.

![error2](https://user-images.githubusercontent.com/7991658/29859298-0ab4208e-8d94-11e7-8ea6-15b488728831.JPG)

![image](https://user-images.githubusercontent.com/7991658/29859295-021392b6-8d94-11e7-83c6-ce93f9ba2b65.png)

Thanks.

**Comment by rdvojmoc** [comment]
Error that you marked shouldn't have any impact on conversion process.
Can you write PDF to disk on a server to confirm that there is something wrong with the library?
```csharp
[HttpGet("booking-preview/{bookingId}")]
public IActionResult GetBookingPreview(long bookingId)
{
	if (!ModelState.IsValid)
		return Ok(ModelState);

	var doc = new HtmlToPdfDocument()
	{
		GlobalSettings = {
			PaperSize = PaperKind.A3,
			Orientation = Orientation.Landscape,
		},

		Objects = {
			new ObjectSettings()
			{
				Page = "http://google.com/",
			},
			new ObjectSettings()
			{
				Page = "https://github.com/",

			}
		}
	};
	byte[] pdf = _converter.Convert(doc);
       //this writes pdf to disk
        using (FileStream stream = new FileStream(@"Files\" + DateTime.UtcNow.Ticks.ToString() + ".pdf", FileMode.Create))
        {
                stream.Write(pdf, 0, pdf.Length);
         }
	return new FileContentResult(pdf, "application/pdf");
}
```

**Comment by jinhduong** [comment]
Thank so much for your quickly answer @rdvojmoc  . The convert work very well and the file save in the server is OK , I 
think I have something wrong when I return the data to client side.

The below code still run to return the pdf file? I got it in your sample.
``` c#
return new FileContentResult(pdf, "application/pdf");
```

Thanks.

**Comment by rdvojmoc** [comment]
Glad that I can help. `FilContentResult` works when I try it on NET Core 1.1. On which version are you?
Can you check with Chrome (F12 - developer tools) if right Content-Type is send from server for PDF that is returned by your `GetBookingPreview` action ?

**Comment by jinhduong** [comment]
I using NET Core 1.1 also. Here is the response result which received in client side (Angular 2+)
![image](https://user-images.githubusercontent.com/7991658/29861727-cb3fe47a-8d9c-11e7-9f04-bd9365a7e834.png)

One more thing is I use Postman to do it but it still happen error. Just made the pdf file by `stream` is OK.

This is my code in client side
``` js
async previewBooking() {
    const result: any = await this._bookingService.getBookingPreview(this.bookingModel.rowId).toPromise();
    const mediaType = 'application/pdf';
    const blob = new Blob([result._body], { type: mediaType });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
  }
```
Thank again @rdvojmoc .

**Comment by rdvojmoc** [comment]
So if I understand correctly the problem with saving PDF on client side is only there if you are using Postman? If you stream it "the old fashion way" the PDF is OK?

**Comment by jinhduong** [comment]
I mean is I have 2 ways to get the pdf file (all wrong): 
- Request to the api to get bytes[] for pdf file and then will using `Blob` to load it. 
- Using Postman to do it.

And if I stream it by `FileStream` it was OK. 😅

**Comment by rdvojmoc** [comment]
Can you paste this to your browser URL box:
`<insert your web server address>/booking-preview/12`

This will return file stream directly from your server.

**Comment by jinhduong** [comment]
That right. It was appeared, thanks, but I also need to add the `bearer` token into request to authentication.

**Comment by rdvojmoc** [comment]
It think that you have a problem with Postman and Angular. I will close this issue.

**Comment by jinhduong** [comment]
I think so, thanks.
