### ISSUE TITLE
Table Header is Repeated on each page

### ISSUE THREAD

**Issue by jwhijazi** [rdvojmoc/DinkToPdf#7]
When I generate PDF from Razor View in .Net Core which contains an Html table, the table header is repeated on each page of the PDF generated Document.
the Repeated header on the second page and down overwrite the table content, while it's fixed right only in the first page.

**Comment by rdvojmoc** [comment]
This is wkhtmltopdf issue. Check [this](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3319) or [this](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3356) issue.

**Comment by jwhijazi** [comment]
#### I solved it by removing the **<thead>** tags from the Table.
But, I will try the suggested CSS style from one of the cases you provided, hope it will help:

<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
</style>

**Comment by MarcusBullock** [comment]
Another solution is to just not use **`<thead>`** in your table. 

Convert your **`<thead>`** to a simple **`<tr>`**.
