### ISSUE TITLE
parameter for --window-status

### ISSUE THREAD

**Issue by gokhangencer** [rdvojmoc/DinkToPdf#75]
Hi,

Is there a way of passing --window-status parameter to libwkhtmltox?

currently JSDelay parameter exist in HtmlToPdfDocument.ObjectSettings.LoadSettings.JSDelay.

Can you add WindowStatus parameter if not presented? 

Thanks in Advanced.

**Comment by gokhangencer** [comment]
any response, please.

**Comment by nicknijenhuis** [comment]
@gokhangencer How did you solve this?

**Comment by gokhangencer** [comment]
1) if you only use windows IIS you can use wkhtmltopdf exe to convert pdf. You can use  System.Diagnostics.ProcessStartInfo to handle this. Calling exe is twice long executing according to calling lib version. I closed this thread because there is no response.

2) Puppeteer-Sharp can be used (in my case I used that for both Linux & Windows hosting). It has event waiting for js code inside the HTML, like so;

var watchDog = page.WaitForFunctionAsync("() => window.status == 'rendered'");

Note:  Puppeteer-Sharp uses headless chromium, I guess exporting pdf is use 300 dpi(no config or param I could find to change). I use Puppeteer-Sharp for generating HTML with full js executed, then I use DinkToPdf for better output result (600dpi, I guess)

**Comment by gokhangencer** [comment]
You can use wkhtmltopdf exe to convert pdf. You can use System.Diagnostics.ProcessStartInfo to handle this. Calling exe is twice long executing according to calling lib version. I closed this thread because there is no response.
