### ISSUE TITLE
Unable to load wkhtmltopdf dll

### ISSUE THREAD

**Issue by Swazimodo** [rdvojmoc/DinkToPdf#8]
I am using this in an ASP.NET Core project that builds against the .NET Framework 4.7. It is running in Kestrel behind IIS.

If I try to load the 32 bit version I get this exception:
> Managed Debugging Assistant 'PInvokeStackImbalance'  occurred
>   Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'DinkToPdf!DinkToPdf.WkHtmlToXBindings::wkhtmltopdf_init' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

If I try to load the 64 bit version I get this exception instead:
> An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by BlueMarmalade** [comment]
does this even work with .net core 2.0?

**Comment by Swazimodo** [comment]
I was never able to make it work and gave up. I'm going to render the HTML and they can print to PDF if they choose.

**Comment by madking2010** [comment]
just add dll files in root folder i tested it works

**Comment by Swazimodo** [comment]
I did try that and you can see by the error messages that it did attempt to load the DLL and failed for both x86 and x64

**Comment by Just3F** [comment]
@madking2010 i need to put 64 bit or 32 bit folder in place where placed .sln file?

**Comment by madking2010** [comment]
![libwkhtmltox](https://user-images.githubusercontent.com/8521584/31310887-b20ff298-aba0-11e7-8f67-ff7958bf7c6b.png)

as you can see in image you have to drag and drop three files in your root folder where you have startup.cs placed

**Comment by Hofmanix** [comment]
Hi, i just had a same problem.
It appeared that because i was using docker and running app on the linux, libwkhtmltox couldnt use screen and was missing some other libraries. I found help in this article: http://dan.clarke.name/2017/05/using-wkhtmltopdf-with-docker/.

In short..there are two things you have to do...First is to have new libwkhtmltox library...at least 0.12.4..breacuse it can work in headless mode.  Second is to have libraries installed which libwkhtmltox needs..this script should do it
`apt-get install -y --no-install-recommends zlib1g fontconfig libfreetype6 libx11-6 libxext6 libxrender1`
Good luck :)

**Comment by Swazimodo** [comment]
@madking2010 I only put the .dll file in the root not the other two. Could you confirm what the purpose of the the other two is? I don't recognize those extensions.

**Comment by Teo-ti** [comment]
On Ubuntu 16.04 (.net core 2.0) I put the files into project root. Also made them executable with chmod +x just in case. Packages recommended by @Hofmanix already installed/latest. But I still get:

> {"error":"Unable to load DLL 'libwkhtmltox': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)"}

**Comment by rdvojmoc** [comment]
Can you try this `apt-get install -y libgdiplus` ? It does similar to what @Hofmanix  suggested.

**Comment by Teo-ti** [comment]
Yes I just tried it and it says: 

>  ~ sudo apt-get install -y libgdiplus
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgdiplus is already the newest version (4.2-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

So I should have all the required dependencies. Just now I even tried to install the libwkhtmltox package with sudo apt-get install, but still no success.

**Comment by Teo-ti** [comment]
The strange thing is that it worked perfectly on my home computer on a Windows 10 64bit.
But in my workplace we have Ubuntus (16.04) and every time I get this error message.

**Comment by Hofmanix** [comment]
Stupid question but couldn't it be that you are building your project with dotnet on Ubuntu? Then the created dll of your program is looking for library in its local folder and not in projects root directory.
I know its stupid but it is the last thing that came to my mind right now. :-D

**Comment by Teo-ti** [comment]
Not a stupid question at all ;)
I thought about that too, so I put all three libwkhtmltox files into _myproject/bin/Debug/netcoreapp2.0_ folder next to _myproject.dll_ file. Still getting "Unable to load DLL 'libwkhtmltox'".

**Comment by challe** [comment]
I just ran in to this problem on my windows machine. Where exactly are you supposed to place the files?

**Comment by Teo-ti** [comment]
I kinda solved my problem but not in the most elegant way. I put all three files right next to the DinkToPdf.dll in the nuget packages folder.
I.e.: ~/.nuget/packages/dinktopdf/1.0.8/lib/netstandard1.6
It's a start but I will continue searching for a better solution.

**Comment by Hofmanix** [comment]
Couldn't it be that it u create debug version it will be connected to the dlls in the packages and if u create publish release version, then the packages will be moved and used in the same folder as yours program dll? Then it should work that if u create package by dotnet publish and put wkhtml files to folder with your published app it should work.

**Comment by Teo-ti** [comment]
Yes, thank you for your suggestion @Hofmanix . It also works if I first run `dotnet publish` and then copy the three libwkhtmltox files to `myproject/bin/Debug/netcoreapp2.0/publish` folder, then run `dotnet myproject.dll`.

So the DinkToPdf package on my Ubuntu 16.04 works only if the native dlls are right next to the DinkToPdf.dll. For some reason, it does not work just by putting them into my project root folder. In my opinion, it's probably just some configuration mishaps.

**Comment by Hofmanix** [comment]
IT could be problem of dotnet itself... Maybe specifying project root directory when running dotnet somehow? Or in csproj? I'm just guessing now.

**Comment by shawinder** [comment]
Please let me know how we can do `page-breaks` for our documents. I will be generating a multi-page report using razor views. I have setup everything else and it works great!

**Comment by Just3F** [comment]
@shawinder pretty easy. just need to add this style `style='page-break-after: always;'` for your element witch you want replace to new line. For example i use this way: `<div style='page-break-after: always;'></div>`

**Comment by shawinder** [comment]
thanks @Just3F !
