### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'D:\YeatsApi\64 bit\libwkhtmltox' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by BTMutturaj** [rdvojmoc/DinkToPdf#84]
I added the workaround from the #5 and it is working working if run through visual studio 17 but when I'm trying to publish it to either azure or local IIS its failing with the following error can some one please help with this.

An error occurred while starting the application.
DllNotFoundException: Unable to load DLL 'D:\YeatsApi\64 bit\libwkhtmltox' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(string unmanagedDllPath)

DllNotFoundException: Unable to load DLL 'D:\YeatsApi\64 bit\libwkhtmltox' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(string unmanagedDllPath)
System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(string unmanagedDllPath)
Socrates.ApiServices.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            services.AddSingleton(typeof(IConverter), new SynchronizedConverter(new PdfTools()));
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by ghost** [comment]
did you set it to Always Copy?

**Comment by BTMutturaj** [comment]
There was some issue with csproj file , fixed it. 
Thank you!!!
