### ISSUE TITLE
letter spacing in css is not working

### ISSUE THREAD

**Issue by aleksa-kuzman** [rdvojmoc/DinkToPdf#89]
I have used DinkToPdf to create some PDF reports on my .net core web api. I included UserStyleSheet in ObjectSettings, but letter spacing is not working for some reason, so I'm realy eager to know if I'm doing something wrong or if letter spacing is not supported by the library. Enjoyed using library very much btw.

Here is the css code
```
h1 {
    text-align: center;
    font-weight: 700;
    font-size: 36px;
    margin-top: 30px;
    letter-spacing: 10px;
}

td, th {
    letter-spacing: 10px;
    height: 35px;
    border-bottom: 1px solid #dedede;
}
```

and here are the object settings:

```
  var objectSettings = new ObjectSettings
            {
                PagesCount = true,
                HtmlContent = UnitOfWork.Ucenici.htmlListaRangiranih(muski,zenski),
                
                WebSettings = { DefaultEncoding = "utf-8" ,UserStyleSheet = Path.Combine( _hostingEnvironment.WebRootPath,"PDFStyles","PDFstyle.css")},
                HeaderSettings = { FontName = "Arial", FontSize = 9 },
                FooterSettings = { FontName = "Arial", FontSize = 9 }
            };
```

**Comment by zadeabhi** [comment]
There is an option smart shrink

**Comment by aleksa-kuzman** [comment]
Thank you

**Comment by tenkyu** [comment]
Hey guys, how can we fix this? I could not find that option anywhere.

**Comment by arunkumaryoyo** [comment]
> There is an option smart shrink

What was the option @zadeabhi

**Comment by cypherrk** [comment]
Stumbled accross this issue and spent time looking for "disable-smart-shrinking" settings. Anyone looking for this can use **EnableIntelligentShrinking** settings in **WebSettings**.
