### ISSUE TITLE
Not working in azure web app

### ISSUE THREAD

**Issue by erikthiago** [rdvojmoc/DinkToPdf#91]
Any suggestions on how to configure dink to pdf to run on azure web app? because I am using it and it works normally locally, however, when I publish in azure web app, it gives timeout just when converting to pdf ... Timeout or other error...

My code:
var obj = _mapper.Map <Result <Model>> (_ modelRepository.GetPaged (
            new ModelsSearch ()
            {
                ItemsForPage = int.MaxValue,
                Page = 1
            }));

            obj .Items.Include (units: _Service.GetAreas () unit, Situations: _Service.GetAll ());

            var doc = new HtmlToPdfDocument ()
            {
                GlobalSettings = {
                ColorMode = ColorMode.Color,
                Orientation = Orientation.Portrait,
                PaperSize = PaperKind.A4,
                Margins = new MarginSettings {
                    Top = 15,
                    Left = 3,
                    Bottom = 8,
                    Right = 2
                },
                DocumentTitle = "Model_Report" + DateTime.Now.ToShortDateString ()
                },
                Objects = {
                    new ObjectSettings () {
                        PagesCount = true,
                        HtmlContent = await _viewRenderService.RenderToStringAsync ("Reports / Model / Model", obj.Items),
                        WebSettings = {DefaultEncoding = "utf-8"},
                         FooterSettings = {
                            FontSize = 9,
                            Right = "Page to [toPage]",
                            Left = $ "{_ environment.EnvironmentName}",
                            Center = $ "Issued By: {_webContext.CurrentUser.DisplayName}",
                            Line = true,
                            Spacing = -4
                        },
                        HeaderSettings = {
                            HtmUrl = Path.Combine (_environment.ContentRootPath, "wwwroot / _Header.html"),
                            Spacing = -4,
                        }
                    }
                }
            };

            try
            {
                byte [] pdf = _converter.Convert (doc); <- here the error
                return File (pdf, "application / pdf");
            }
            catch (Ex Exception)
            {
                return Ok (ex.Message);
            }

I even put a try / catch, but still couldn't catch the exception.

**Comment by ejcortes** [comment]
I'm here too... It just hangs and ends up with "The specified CGI application encountered an error and the server terminated the process."

Locally, it runs perfect. Converter is on a singleton as sugested. I'm lost here.

**Comment by AdminFSP** [comment]
check this https://www.nuget.org/packages/Haukcode.DinkToPdf

**Comment by erikthiago** [comment]
Guys, the problem is: sandbox on azure block the run of other files that we need. To workaround this: use docker linux or use an VM.

**Comment by milons** [comment]
For me, it worked to change x64 libraries to x86 (libwkhtmltox.dll).

**Comment by marexv** [comment]
@milons Hey that is great news, can you elaborate a bit? Where did you have to change it?

**Comment by marexv** [comment]
> check this https://www.nuget.org/packages/Haukcode.DinkToPdf

How does that library differ? Does it work on azure?

**Comment by AliRafay** [comment]
Any Update?

**Comment by darkderes** [comment]
Thanks @milons,  I changed X64 libraries to X86 and work ..
